### PR TITLE
Return an error if server_name is missing

### LINKED ISSUE #65: Failing to supply a server_name causes a 502 which causes a Cloud Flare screen
This isn't a big deal because it should be obvious what your mistake is, but it's rather unfriendly to show the user a screen saying matrix.org is down rather than asking them to specify a server_name.

### PR DESCRIPTION
**Pull request by babolivier**
Fixes #65

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -37,6 +37,11 @@ func HandleReport(w http.ResponseWriter, req *http.Request) {
 		return
 	}
 	serverName := gomatrixserverlib.ServerName(req.URL.Query().Get("server_name"))
+	if len(serverName) == 0 {
+		w.WriteHeader(400)
+		fmt.Printf("Missing server_name.\n")
```
Comment (richvdh) [inline main.go]: shouldn't this go to the response rather than (or maybe as well as) stdout?

Comment (babolivier) [reply main.go]: Unsure, I used what we do for `GET` requests as an example, which is:

```golang
if req.Method != "GET" {
	w.WriteHeader(405)
	fmt.Printf("Unsupported method.\n")
	return
}
```

**Comment by babolivier** [comment]
> I'm not convinced we should send error responses as json - why not just send the plain text?

Because I thought it would make it easier for people building on top of the federation tester if we use an existing JSON property instead of making special cases in which the federation tester would not follow the response schema it follows for every other requests, as long as possible.
